### ISSUE TITLE
TOPページの導線は分かりづらい

### ISSUE THREAD

**Issue by jp-knj** [s19013/my-wiki#17]
# 概要
TOPページへ遷移した時、つぎの行動をしづらかった。

# 目的
ユーザーの導線を意識して、カラーを設定してほしいため

# 提案内容
現状のリンクカラーが背景と同系色なため、変更してほしい

**現状**
![スクリーンショット 2022-08-16 23 12 50](https://user-images.githubusercontent.com/70939128/184901850-d19b7097-ef25-476a-a1ca-56b3f65f03c2.png)

**変更後**
![スクリーンショット 2022-08-16 23 13 26](https://user-images.githubusercontent.com/70939128/184901871-a691ae50-47f4-4e62-846a-fc20418bec72.png)

# タスク
- [ ] 細かいタスクに分解できているなら書き出す

# 再現手順
1. TOPページへ遷移 (http://35.230.90.39/)

**Comment by s19013** [comment]
ダークモード対策をする
